// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQkjdO6KuMys0AfilL1AXGMF7vlXXGZI8',
    appId: '1:1567403296:web:1050907539ae3703897b45',
    messagingSenderId: '1567403296',
    projectId: 'africafood-3c342',
    authDomain: 'africafood-3c342.firebaseapp.com',
    storageBucket: 'africafood-3c342.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHD0uSae2GoHU050LIm2sTGq3sccHi_jc',
    appId: '1:1567403296:android:3ea9a384740770b9897b45',
    messagingSenderId: '1567403296',
    projectId: 'africafood-3c342',
    storageBucket: 'africafood-3c342.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7MS_wTazWcAXpb0_DkE1Hu0KIIdODoGA',
    appId: '1:1567403296:ios:56c360c20141e810897b45',
    messagingSenderId: '1567403296',
    projectId: 'africafood-3c342',
    storageBucket: 'africafood-3c342.appspot.com',
    iosClientId: '1567403296-bvasqv804p1rtcplfq5gth69tmapfi0h.apps.googleusercontent.com',
    iosBundleId: 'com.dynamic.africafood',
  );
}
